### PR TITLE
Added FAWE and FAVS project logo to gitbook homepage

### LINKED ISSUE #39: Add the project's logo to the home page FAWE and FAVS
https://intellectualsites.gitbook.io/fastasyncworldedit/ and https://intellectualsites.gitbook.io/fastasyncvoxelsniper/ should have a small title icon, similar to https://intellectualsites.gitbook.io/plotsquared/

### PR DESCRIPTION
**Pull request by specbeck**
## Overview

Fixes #39 

## Description

Adds respective project logos to the homepages rendered by gitbook as a tile as per the structure used in https://intellectualsites.gitbook.io/plotsquared/

### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NotMyFault** [comment]
Can't we use the SVG from the asset repo with scaling?

**Comment by NotMyFault** [comment]
> Sure, I'll do that

I meant as raw URL, instead of duplicating the content by adding images.

**Comment by specbeck** [comment]
> I meant as raw URL, instead of duplicating the content by adding images.
Oh, apologies. Is the same needed to be done for FAVS logo too?

**Comment by NotMyFault** [comment]
No

**Review by Aurelien30000 — APPROVED** [review]
LGTM! Thanks

**Comment by NotMyFault** [comment]
You forgot to include the FAWE logo.

**Comment by specbeck** [comment]
Wasn't that supposed to be added as a raw URL?

**Comment by NotMyFault** [comment]
> Wasn't that supposed to be added as a raw URL?

Surely, but the icon should come from the asset repo, not as blog from a commit.

**Comment by specbeck** [comment]
I tired adding the asset link directly, as in b54ee2a970ea06bf15668da054b57675d81d05b5, but it didn't render the logo.

**Comment by NotMyFault** [comment]
> I tired adding the asset link directly, as in [b54ee2a](https://github.com/IntellectualSites/documentation/commit/b54ee2a970ea06bf15668da054b57675d81d05b5), but it didn't render the logo.
> 
> I'd very much like to know what went wrong :)

You'll need to use the direct image URL, such as https://raw.githubusercontent.com/IntellectualSites/Assets/main/plugins/FastAsyncWorldEdit/FastAsyncWorldEdit.svg

**Comment by specbeck** [comment]
Thanks, all set to go

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
